### ISSUE TITLE
TabButton component

### ISSUE THREAD

**Issue by Imater** [Imater/4team#11]
![Табы](http://s.csssr.ru/U0Y1QRYG7/20171110002701.png)

- Умеет быть isPinned, тогда он квадратный
- Рендерит children текст
- Принимает icon свойство в которое можно передать компонент с иконкой или просто символ "А"
- поддерживает цвет фона 
- цвет шрифта
- может быть disabled
- active - если активен, показывает 2х пиксельную линию цвета, заданного в теме внизу, по умолчанию белую
- показывает полное название при наведении
- длинные названия скрывает многоточием ellepsis
- isCloseButtonVisible - умеет отображать крестик внутри, если он передан в props
- haveCloseButton - оставляет место под крестик
- При нажатии на него или на крестик вызывает методы, переданные ему в пропсы
- Имеет свойство, по которому скрывает место, где иконка, если он не isPinned, чтобы можно было в настройках приложения отключать иконки в табах

**Comment by IgorYarutkin** [comment]
#19 PR Make TabComponent

**Comment by Imater** [comment]
done
