### ISSUE TITLE
Box component

### ISSUE THREAD

**Issue by Imater** [Imater/4team#6]
Добавить компонент квадратик с возможностью закруглить любой из уголков и размещать иконку в центре. При увеличении родителя по высоте, растягивать по высоте, оставляя иконку на прежнем месте сверху.
![BoxComponent](https://pp.userapi.com/c619220/v619220778/2385/DjEO3TeFfVs.jpg)

**Comment by IgorYarutkin** [comment]
Размер шрифта и верхнего падинга по умолчанию какие?

**Comment by Imater** [comment]
https://pp.userapi.com/c616518/v616518778/10e37/5AQ_SlS0jWY.jpg
Вот оригинальный макет в картинке. Размеры надо такие.

**Comment by IgorYarutkin** [comment]
#13 Box Component

**Comment by Imater** [comment]
done
